############################################### 
#   Extreme Deconvolution yaml settings
############################################### 

fitting : True
train_sample : /n/des/lee.5922/cmass_cat/CMASS_SGC_photoObj.fits
cmass_pickle : pickle/gold_st82_2zbin_1st_XD_cmass.pkl
no_pickle : pickle/gold_st82_2zbin_1st_XD_no.pkl
cmass_fraction : 0.016306526563
#n_cmass : 6  
#n_no : 27

cat_area : st82
input_cat_dir : /n/des/lee.5922/data/gold_cat/
input_cat_keyword : Y1A1_GOLD_STRIPE82_v2 # Y1A1_GOLD_00 #Y1A1_GOLD_STRIPE82_v2
out_catname : result_cat/gold_st82_prob.fits
out_resampled_cat : result_cat/dmass_st82.fits
