############################################### 
#   Extreme Deconvolution yaml settings
############################################### 

fitting : False
train_sample : /n/des/lee.5922/data/cmass_cat/galaxy_DR12v5_CMASS_South_z0_055.fits.gz
random_sampling : True  #If ~train sample is too big

cmass_pickle : pickle/gold_st82_XD_cmass.pkl
no_pickle : pickle/gold_st82_XD_no.pkl

#cmass_fraction : 0.016306526563
# If not given, program finds an optimal value
n_cmass : 5  
n_no : 25

input_cat_dir : /n/des/lee.5922/data/gold_cat/
input_cat_keyword : Y1A1_GOLD_00 #Y1A1_GOLD_STRIPE82_v2
cat_area :  # if not st82, leave it empty
out_catname : result_cat/gold_spt_prob.fits
out_resampled_cat : result_cat/dmass_spt.fits
