############################################### 
#   Extreme Deconvolution yaml settings
############################################### 

fitting : False
random_sampling : True
output_dir : output/sfd_train_com5_10/
train_sample : /n/des/lee.5922/data/cmass_cat/galaxy_DR12v5_CMASS_South.fits.gz
cmass_pickle : gold_st82_XD_cmass.pkl
no_pickle : gold_st82_XD_no.pkl
num_mock : 10
cmass_fraction : cmassfrac
n_cmass : 5  
n_no : 10

#cat_area : st82
#input_cat_dir : /n/des/lee.5922/data/gold_cat/
#input_cat_keyword : Y1A1_GOLD_STRIPE82_v2_0000
#out_catname : gold_st82_prob.fits
#out_resampled_cat : dmass_st82
SFD98 : True
cat_area : spt
input_cat_dir : /n/des/lee.5922/data/gold_cat/
input_cat_keyword : Y1A1_GOLD_00
out_catname : gold_spt_prob
out_resampled_cat : dmass_spt
