############################################### 
#   Extreme Deconvolution yaml settings
############################################### 

fitting : False
cmass_pickle : pickle/gold_st82_XD_cmass.pkl
no_pickle : pickle/gold_st82_XD_no.pkl
cmass_fraction : 0.016306526563
#n_cmass : 6  
#n_no : 27

input_cat_dir : /n/des/lee.5922/data/gold_cat/
input_cat_keyword : Y1A1_GOLD_STRIPE82_v2 # Y1A1_GOLD_00 #Y1A1_GOLD_STRIPE82_v2
out_catname : result_cat/gold_st82_prob.fits
out_resampled_cat : result_cat/dmass_st82.fits
